version: "3.8"

services:
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./logs:/var/log/nginx
